title: "420-930-MA"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

collections:
  seances:
    output: true
    permalink: /:collection/:name

just_the_docs:
  collections:
    seances:
      name: SÃ©ances
      nav_fold: true

