title: "Algorithmes et modèles de programmation"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

collections:
  seances:
    output: true
    permalink: /:collection/:name

just_the_docs:
  collections:
    seances:
      name: Séances
      nav_fold: true

